name: ultra_wide_turbo_cli
description: A command-line tool for managing Ultra Wide Turbo development workflows. Features auto-updates, workspace management, and comprehensive documentation.
version: 0.1.5
repository: https://github.com/ultrawideturbodev/ultra_wide_turbo_cli
homepage: https://ultrawideturbodev.com
documentation: https://github.com/ultrawideturbodev/ultra_wide_turbo_cli/tree/main/turbo_docs
issue_tracker: https://github.com/ultrawideturbodev/ultra_wide_turbo_cli/issues
topics:
  - cli
  - development
  - workflow
  - automation

executables:
  turbo:

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.6.0
  cli_completion: ^0.5.1
  get_it: ^8.0.3
  hive_ce: ^2.9.0
  mason_logger: ^0.3.1
  meta: ^1.11.0
  path: ^1.9.1
  pub_updater: ^0.5.0
  json_annotation: ^4.9.0
  turbo_response: ^0.2.3

dev_dependencies:
  json_serializable: ^6.9.2
  build_runner: ^2.4.14
  build_verify: ^3.1.0
  build_version: ^2.1.1
  lints: ^5.1.1
  test: ^1.25.14
  very_good_analysis: ^7.0.0
  mocktail: ^1.0.1
