// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:ultra_wide_turbo_cli/core/dtos/local_storage_dto.dart';
import 'package:ultra_wide_turbo_cli/core/dtos/turbo_relation_dto.dart';
import 'package:ultra_wide_turbo_cli/core/dtos/turbo_source_dto.dart';
import 'package:ultra_wide_turbo_cli/core/dtos/turbo_tag_dto.dart';
import 'package:ultra_wide_turbo_cli/core/dtos/turbo_target_dto.dart';
import 'package:ultra_wide_turbo_cli/core/enums/turbo_relation_type.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LocalStorageDtoAdapter());
    registerAdapter(TurboRelationDtoAdapter());
    registerAdapter(TurboRelationTypeAdapter());
    registerAdapter(TurboSourceDtoAdapter());
    registerAdapter(TurboTagDtoAdapter());
    registerAdapter(TurboTargetDtoAdapter());
  }
}
